import Link from 'next/link';

export const metadata = { title: 'Terms of Service — Drashai' };

export default function TermsOfService() {
  return (
    <div style={{
      minHeight: '100vh',
      background: 'var(--bg-page)',
      padding: '48px 16px',
    }}>
      <article className="card" style={{
        maxWidth: 720,
        margin: '0 auto',
        padding: '40px 36px',
        fontFamily: "'Cormorant Garamond', serif",
        color: 'var(--ink)',
        lineHeight: 1.7,
        fontSize: 16,
      }}>
        <h1 className="heb-display" style={{ fontSize: 28, margin: '0 0 4px' }}>Terms of Service</h1>
        <p className="mono" style={{ fontSize: 11, color: 'var(--ink-3)', letterSpacing: '0.08em', margin: '0 0 32px' }}>
          Last updated: May 26, 2026
        </p>

        <p>
          By using Drashai ("the app"), you agree to these terms. If you do not
          agree, please do not use the app.
        </p>

        <Section title="1. Description of Service">
          <p>Drashai is an encounter recorder and content generator designed for rabbis. It allows you to record encounters, transcribe audio, generate written content with AI assistance, and manage files in Google Drive.</p>
        </Section>

        <Section title="2. Account & Access">
          <p>You sign in using your Google account. You are responsible for maintaining the security of your Google credentials. Access to Drashai may be limited or invitation-based at our discretion.</p>
        </Section>

        <Section title="3. Your Content">
          <p>You retain full ownership of all recordings, transcripts, notes, and generated content created through the app. We do not claim any intellectual property rights over your content.</p>
          <p>By using the app, you grant us a limited license to process your content solely for the purpose of providing the service (e.g., sending text to AI for generation, storing files in your Drive).</p>
        </Section>

        <Section title="4. AI-Generated Content">
          <p>Content generated by AI (via Anthropic Claude) is provided as a draft and starting point. You are responsible for reviewing, editing, and verifying all AI-generated content before use. We make no guarantees about the accuracy, completeness, or appropriateness of AI outputs.</p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to:</p>
          <ul style={{ paddingLeft: 20, margin: '8px 0' }}>
            <li>Use the app for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to the app or its systems</li>
            <li>Interfere with or disrupt the service</li>
            <li>Share your account access with unauthorized parties</li>
          </ul>
        </Section>

        <Section title="6. Third-Party Services">
          <p>The app integrates with Google, Anthropic, ElevenLabs, and Vercel. Your use of these services through the app is also subject to their respective terms of service.</p>
        </Section>

        <Section title="7. Availability & Changes">
          <p>We strive to keep the app available but do not guarantee uninterrupted access. We may modify, suspend, or discontinue features at any time. We will make reasonable efforts to notify you of significant changes.</p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>The app is provided "as is" without warranties of any kind, express or implied. To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the app.</p>
        </Section>

        <Section title="9. Termination">
          <p>We may suspend or terminate your access at any time for violation of these terms. You may stop using the app at any time and revoke access via your Google account settings.</p>
        </Section>

        <Section title="10. Changes to Terms">
          <p>We may update these terms from time to time. Continued use of the app after changes constitutes acceptance of the revised terms.</p>
        </Section>

        <div style={{ marginTop: 32, paddingTop: 20, borderTop: '1px solid var(--border)' }}>
          <Link href="/login" style={{ color: 'var(--accent)', fontSize: 14 }}>← Back to login</Link>
          {' · '}
          <Link href="/privacy" style={{ color: 'var(--accent)', fontSize: 14 }}>Privacy Policy</Link>
        </div>
      </article>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ margin: '24px 0' }}>
      <h2 style={{ fontSize: 18, fontWeight: 600, margin: '0 0 8px' }}>{title}</h2>
      {children}
    </section>
  );
}
